
  - name: Install zabbix.repo
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm


  - name: Install Zabbix Agent
    yum:
      name: zabbix-agent
      state: present
    become: true


  - name: "Deploying {{ zabbix_remote_conf_dir }}/{{ zabbix_agent_remote_conf }}"
    template:
      src:  "{{ files_dir }}/{{ zabbix_agent_conf }}"
      dest: "{{ zabbix_remote_conf_dir }}/{{ zabbix_agent_remote_conf }}"
    notify: Restart zabbix-agent
    become: true


  - name: "Start and enable zabbix-agent"
    service:
      name: zabbix-agent
      state: started
      enabled: yes
    become: true


  - name: "Waiting for zabbix agent to be ready"
    wait_for:
      port:  "{{ zabbix_agent_port }}"
      delay:   "{{ zabbix_agent_delay }}"
      timeout: "{{ zabbix_agent_timeout }}"


